name: Django Admin

#on:
#  push:
#    branches: [ master ]
#  workflow_dispatch:

on:
  push:
    branches: [ testWorkflow ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MARIADB_ROOT_PASSWORD: ourRootPassword
          MYSQL_DATABASE: djangoDatabase
          MYSQL_USER: djangoUser
          MYSQL_PASSWORD: yourPassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Environment settings
        run: |
          cp .env.example .env
          awk -v var="DB_ENGINE=mysql" '/^DB_ENGINE=/{print var; next} 1' .env > temp && mv temp .env
          awk -v var="SECRET_KEY=django-insecure-2!@#4qwer" '/^SECRET_KEY=/{print var; next} 1' .env > temp && mv temp .env
          cat .env

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test